services:
  - type: web
    name: mychatbackend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.3
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 86400
      - key: ALLOWED_ORIGINS
        value: "*"
